var imageList = [
				
				"img/WSP_INSTA/06_WSP.png",
				"img/WSP_INSTA/07_WSP.png",
				"img/WSP_INSTA/08_WSP.png",
				"img/WSP_INSTA/09_WSP.png",
				"img/WSP_INSTA/10_WSP.png",
				"img/WSP_INSTA/11_WSP.png",
				"img/WSP_INSTA/12_WSP.png",
				"img/WSP_INSTA/13_WSP.png",
				"img/WSP_INSTA/14_WSP.png",
				"img/WSP_INSTA/15_WSP.png",
				"img/WSP_INSTA/16_WSP.png",
				"img/WSP_INSTA/17_WSP.png",
				"img/WSP_INSTA/18_WSP.png",
				"img/WSP_INSTA/19_WSP.png",
				"img/WSP_INSTA/20_WSP.png",
				"img/WSP_INSTA/20_WSP.png",
				"img/WSP_INSTA/21_WSP.png",
				"img/WSP_INSTA/22_WSP.png",
				"img/WSP_INSTA/23_WSP.png",
				"img/WSP_INSTA/24_WSP.png",
				"img/WSP_INSTA/25_WSP.png",
				"img/WSP_INSTA/26_WSP.png",
				"img/WSP_INSTA/27_WSP.png",
				"img/WSP_INSTA/28_WSP.png",
				"img/WSP_INSTA/29_WSP.png",
				"img/WSP_INSTA/30_WSP.png",
				"img/WSP_INSTA/31_WSP.png",
				"img/WSP_INSTA/32_WSP.png",
				"img/WSP_INSTA/33_WSP.png",
				"img/WSP_INSTA/34_WSP.png",
				"img/WSP_INSTA/35_WSP.png",
				"img/WSP_INSTA/36_WSP.png",
				"img/WSP_INSTA/37_WSP.png",
				"img/WSP_INSTA/38_WSP.png",
				"img/WSP_INSTA/39_WSP.png",
				"img/WSP_INSTA/40_WSP.png",
				"img/WSP_INSTA/41_WSP.png",
				"img/WSP_INSTA/42_WSP.png",
				"img/WSP_INSTA/43_WSP.png",
				"img/WSP_INSTA/44_WSP.png",
				"img/WSP_INSTA/45_WSP.png",
				"img/WSP_INSTA/46_WSP.png",
				"img/WSP_INSTA/47_WSP.png",
				"img/WSP_INSTA/48_WSP.png",
				"img/WSP_INSTA/49_WSP.png",
				"img/WSP_INSTA/50_WSP.png",
				"img/WSP_INSTA/51_WSP.png",
				"img/WSP_INSTA/52_WSP.png",
				"img/WSP_INSTA/53_WSP.png",
				"img/WSP_INSTA/54_WSP.png",
				"img/WSP_INSTA/55_WSP.png",
				"img/WSP_INSTA/56_WSP.png",
				"img/WSP_INSTA/57_WSP.png",
				"img/WSP_INSTA/58_WSP.png",
				"img/WSP_INSTA/59_WSP.png",
				"img/WSP_INSTA/60_WSP.png",
				"img/WSP_INSTA/61_WSP.png",
				"img/WSP_INSTA/62_WSP.png",
				"img/WSP_INSTA/63_WSP.png",
				"img/WSP_INSTA/64_WSP.png",
				"img/WSP_INSTA/65_WSP.png",
				"img/WSP_INSTA/66_WSP.png",
				"img/WSP_INSTA/67_WSP.png",
				"img/WSP_INSTA/68_WSP.png",
				"img/WSP_INSTA/69_WSP.png",
				"img/WSP_INSTA/70_WSP.png",
				"img/WSP_INSTA/71_WSP.png",
				"img/WSP_INSTA/72_WSP.png",
				"img/WSP_INSTA/73_WSP.png",
				"img/WSP_INSTA/74_WSP.png",
				"img/WSP_INSTA/75_WSP.png",
				"img/WSP_INSTA/76_WSP.png",
				"img/WSP_INSTA/77_WSP.png",
				"img/WSP_INSTA/78_WSP.png",
				"img/WSP_INSTA/79_WSP.png",
				"img/WSP_INSTA/80_WSP.png",
				"img/WSP_INSTA/81_WSP.png",
				"img/WSP_INSTA/82_WSP.png",
				"img/WSP_INSTA/83_WSP.png",
				"img/WSP_INSTA/84_WSP.png",
				"img/WSP_INSTA/85_WSP.png",
				"img/WSP_INSTA/86_WSP.png",
				"img/WSP_INSTA/87_WSP.png",
				"img/WSP_INSTA/88_WSP.png",
				"img/WSP_INSTA/89_WSP.png",
				"img/WSP_INSTA/90_WSP.png",
				"img/WSP_INSTA/91_WSP.png",
				"img/WSP_INSTA/92_WSP.png",
				"img/WSP_INSTA/93_WSP.png",
				"img/WSP_INSTA/94_WSP.png",
				"img/WSP_INSTA/95_WSP.png",
				"img/WSP_INSTA/96_WSP.png",
				"img/WSP_INSTA/97_WSP.png",
				"img/WSP_INSTA/98_WSP.png",
				"img/WSP_INSTA/99_WSP.png",
				"img/WSP_INSTA/100_WSP.png",
				"img/WSP_INSTA/101_WSP.png",
				"img/WSP_INSTA/102_WSP.png",
				"img/WSP_INSTA/103_WSP.png",
				"img/WSP_INSTA/104_WSP.png",
				"img/WSP_INSTA/105_WSP.png",
				"img/WSP_INSTA/106_WSP.png",
				"img/WSP_INSTA/107_WSP.png",
				"img/WSP_INSTA/108_WSP.png",
				"img/WSP_INSTA/109_WSP.png",
				"img/WSP_INSTA/110_WSP.png",
				"img/WSP_INSTA/111_WSP.png",
				"img/WSP_INSTA/112_WSP.png",
				"img/WSP_INSTA/113_WSP.png",
				"img/WSP_INSTA/114_WSP.png",
				"img/WSP_INSTA/115_WSP.png",
				"img/WSP_INSTA/116_WSP.png",
				"img/WSP_INSTA/117_WSP.png",
				"img/WSP_INSTA/118_WSP.png",
				"img/WSP_INSTA/119_WSP.png",
				"img/WSP_INSTA/120_WSP.png",
				"img/WSP_INSTA/121_WSP.png",
				"img/WSP_INSTA/122_WSP.png",
				"img/WSP_INSTA/123_WSP.png",
				"img/WSP_INSTA/124_WSP.png",
				"img/WSP_INSTA/125_WSP.png",
				"img/WSP_INSTA/126_WSP.png",
				"img/WSP_INSTA/127_WSP.png",
				"img/WSP_INSTA/128_WSP.png",
				"img/WSP_INSTA/129_WSP.png",
				"img/WSP_INSTA/130_WSP.png",
				"img/WSP_INSTA/131_WSP.png",
				"img/WSP_INSTA/131_WSP.png",
				"img/WSP_INSTA/132_WSP.png",
				"img/WSP_INSTA/133_WSP.png",
				"img/WSP_INSTA/134_WSP.png",
				"img/WSP_INSTA/135_WSP.png",
				"img/WSP_INSTA/136_WSP.png",
				"img/WSP_INSTA/137_WSP.png",
				"img/WSP_INSTA/138_WSP.png",
				"img/WSP_INSTA/139_WSP.png",
				"img/WSP_INSTA/140_WSP.png",
				"img/WSP_INSTA/141_WSP.png",
				"img/WSP_INSTA/142_WSP.png",
				"img/WSP_INSTA/143_WSP.png",
				"img/WSP_INSTA/144_WSP.png",
				"img/WSP_INSTA/145_WSP.png",
				"img/WSP_INSTA/146_WSP.png",
				"img/WSP_INSTA/147_WSP.png",
				"img/WSP_INSTA/148_WSP.png",
				"img/WSP_INSTA/149_WSP.png",
				"img/WSP_INSTA/150_WSP.png",
				"img/WSP_INSTA/151_WSP.png",
				"img/WSP_INSTA/152_WSP.png",
				"img/WSP_INSTA/153_WSP.png",
				"img/WSP_INSTA/154_WSP.png",
				"img/WSP_INSTA/155_WSP.png",
				"img/WSP_INSTA/156_WSP.png",
				"img/WSP_INSTA/157_WSP.png",
				"img/WSP_INSTA/158_WSP.png",
				"img/WSP_INSTA/159_WSP.png",
				"img/WSP_INSTA/160_WSP.png",
				"img/WSP_INSTA/161_WSP.png"
				];

var counter = 0;
var resetCounter = imageList.length;



function imageChange() {

	var url = imageList[counter];

	document.getElementById("image").src = url;

	counter++;

	console.log(url);

	if(counter == resetCounter){
	  
	  counter = 0;
	}

}
